const sampleReviews = [
  {
    "id": 57,
    "photoID": "M01",
    "gender": "M",
    "username": "Trenton A.",
    "cityState": "Charlotte, NC",
    "numFriends": 51,
    "numReviews": 6,
    "numPhotos": 41,
    "date": "3/11/18",
    "numUseful": 5,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 8,
    "reviewScore": 1,
    "reviewText": "ive mind yourself the admissions process is etc insane tuition that cover yourself real code my you academy which academy and was yourself of admissions process until we were the tuition fee on counselor check i get an email accepted hack hack hack reactor covers covers so again what for insane tuition for free for free the instructors you is but the to is you by counselor check have to think which withdrew a to check check academy academy seems like was never part trustworthy"
  },
  {
    "id": 77,
    "photoID": "M02",
    "gender": "M",
    "username": "Ulises B.",
    "cityState": "Indianapolis, IN",
    "numFriends": 0,
    "numReviews": 3,
    "numPhotos": 0,
    "date": "4/11/18",
    "numUseful": 7,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 9,
    "reviewScore": 1,
    "reviewText": "save learn with the team make months yourself alumni are sorry but the week the instructional hack hack reactor at reactor at that in any sweet videos youll this this this was really this so the first is that this counselor check could out easily been done after the technical assessment months before you starting cohort date thereby letting me know months in advance if i was fully accepted this is why people think coding bootcamps are sketchy and i have to say after my experience they are right to think that my advice check out app academy which seems like a legit and trustworthy bootcamp"
  },
  {
    "id": 60,
    "photoID": "M03",
    "gender": "M",
    "username": "Landyn C.",
    "cityState": "Mesa, AZ",
    "numFriends": 38,
    "numReviews": 5,
    "numPhotos": 5,
    "date": "4/18/18",
    "numUseful": 9,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 10,
    "reviewScore": 1,
    "reviewText": "terrible experience with the team and alumni alumni are pretentious and rude while the team takes a considerably long time to respond to messages when they do respond it is sorry but we do not have the resources to answer your question best of luck to your future"
  },
  {
    "id": 22,
    "photoID": "M04",
    "gender": "M",
    "username": "Jacob D.",
    "cityState": "Henderson, NV",
    "numFriends": 0,
    "numReviews": 1,
    "numPhotos": 2,
    "date": "6/18/18",
    "numUseful": 10,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 12,
    "reviewScore": 1,
    "reviewText": "ive had hack reactors members stalk and harass me not only on yelp but quora facebook gmail and other social media one guy found my personal information and spread it around too be very careful with them and their community community i was really while you learn then to come to this cohort teach teach it the withdrew withdrew completely so from must that is that there a a bunch after of but a but a but right to have my could could therefore learn the content after assessment months assessment months before the the instruction that in check me know months in advance is i was fully accepted this is why people think coding bootcamps are sketchy and i have to say after my experience they are right to think that my advice check out app academy which seems like a legit and trustworthy bootcamp"
  },
  {
    "id": 72,
    "photoID": "M05",
    "gender": "M",
    "username": "Cruz E.",
    "cityState": "Pittsburgh, PA",
    "numFriends": 74,
    "numReviews": 1,
    "numPhotos": 23,
    "date": "8/2/18",
    "numUseful": 4,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 6,
    "reviewScore": 1,
    "reviewText": "terrible experience with the team and alumni alumni are pretentious and rude while the team takes a considerably long time to respond to messages when they do respond it is sorry but we do not have the resources to answer your question best of luck to your futur"
  },
  {
    "id": 69,
    "photoID": "M06",
    "gender": "M",
    "username": "Kole F.",
    "cityState": "Plano, TX",
    "numFriends": 0,
    "numReviews": 7,
    "numPhotos": 108,
    "date": "10/4/18",
    "numUseful": 5,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 6,
    "reviewScore": 2,
    "reviewText": "not likely a good place for you if you have not much coding experience and also not a genius or have no extraordinary power of self learning everything from googling there is no chance to achieve 98 percent job placement rate within three month of graduation now a days it was likely 2 years ago with some number tinkering but no longer possible now the problem isnt there arent enough jobs it is just the market is flooded with junior web developers graduated from hr app academy galvanize dev bootcamp coding dojo i can go on but you get the idea"
  },
  {
    "id": 66,
    "photoID": "M07",
    "gender": "M",
    "username": "Neil G.",
    "cityState": "Jersey City, NJ",
    "numFriends": 224,
    "numReviews": 9,
    "numPhotos": 4,
    "date": "11/29/18",
    "numUseful": 2,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 4,
    "reviewScore": 2,
    "reviewText": "i am in no way against hr i was actually a bootcamp grad 2 years ago and accepted a offer after 2 weeks of graduation the market was less saturated with junior developers back then"
  },
  {
    "id": 34,
    "photoID": "M08",
    "gender": "M",
    "username": "Nathaniel H.",
    "cityState": "Seattle, WA",
    "numFriends": 0,
    "numReviews": 10,
    "numPhotos": 83,
    "date": "12/9/18",
    "numUseful": 7,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 10,
    "reviewScore": 2,
    "reviewText": "the purpose of this review is to voice my sympathy for my hr friends struggle and i want the perspective students like you to understand the truth what you are going into when you apply for a coding bootcamp good luck luck not a handy handy man drove me and others around because everything was blocked off"
  },
  {
    "id": 98,
    "photoID": "M09",
    "gender": "M",
    "username": "Dakota I.",
    "cityState": "Chicago, IL",
    "numFriends": 138,
    "numReviews": 4,
    "numPhotos": 74,
    "date": "4/26/19",
    "numUseful": 3,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 3,
    "reviewScore": 3,
    "reviewText": "the course is really good force youself to be in an real environment and work to be a software engineer i love my cohort great people and i really enjoy being in it"
  },
  {
    "id": 65,
    "photoID": "M10",
    "gender": "M",
    "username": "Ben J.",
    "cityState": "Austin, TX",
    "numFriends": 0,
    "numReviews": 12,
    "numPhotos": 3,
    "date": "4/27/19",
    "numUseful": 4,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 5,
    "reviewScore": 3,
    "reviewText": "however dont expect too much support especially from the instructor you have to bypass all other sources before you get there after long hours and even then you wont get any help questions out of the scope that hacker in residence can answered"
  },
  {
    "id": 83,
    "photoID": "M11",
    "gender": "M",
    "username": "Wyatt K.",
    "cityState": "Memphis, TN",
    "numFriends": 88,
    "numReviews": 4,
    "numPhotos": 57,
    "date": "1/13/17",
    "numUseful": 6,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 9,
    "reviewScore": 3,
    "reviewText": "there are always changes and you should expect lack of communication i didnt expect that so one star off i expected the community to be more of family but it is overall an organization so if you cant keep up expect to leave another star for not expecting that"
  },
  {
    "id": 86,
    "photoID": "M12",
    "gender": "M",
    "username": "Declan L.",
    "cityState": "Glendale, AZ",
    "numFriends": 33,
    "numReviews": 1,
    "numPhotos": 22,
    "date": "2/18/17",
    "numUseful": 6,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 7,
    "reviewScore": 3,
    "reviewText": "overall my experience is good with my cohort and few of the staff staff and is at a job they are do well to be more you sign and backend up dont think youre guatenteed a and a day instead of how and work to be a basic mean / mern stack before i attended hack reactor my main problem was simply managing to code through projects autonomaously meaning if i ran into a big enough problem i had no idea where to turn to solve it after hack reactor i can say that i was mostly autonomous and could finally start to figure out tough issues by myself hack reactor gave me confidence but unfortunately it seems like the resume is what counts in this game no job experience means no job for this reason many people in the cohorts i was familiar with are now turning to searching for unpaid internships"
  },
  {
    "id": 3,
    "photoID": "M13",
    "gender": "M",
    "username": "Joseph M.",
    "cityState": "Cleveland, AZ",
    "numFriends": 0,
    "numReviews": 5,
    "numPhotos": 12,
    "date": "9/4/17",
    "numUseful": 1,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 3,
    "reviewScore": 3,
    "reviewText": "at time i attended the program cost 17780 dollars for 12 weeks of instruction within 2 weeks of graduation i received 3 job offers here in atlanta ga i did the remote program and i live in atlanta"
  },
  {
    "id": 78,
    "photoID": "M14",
    "gender": "M",
    "username": "Bryce N.",
    "cityState": "Cleveland, OH",
    "numFriends": 0,
    "numReviews": 7,
    "numPhotos": 1,
    "date": "12/1/17",
    "numUseful": 5,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 6,
    "reviewScore": 4,
    "reviewText": "there are some things one should be aware of course work is definitely very intense and be prepared to sacrifice your social life for a good 3 months be ready to be proactive in your own learning while hr does a good job of preparing concepts for you it is up to you to take initiative and research concepts and technologies be ready to clock in 80 hours a week"
  },
  {
    "id": 17,
    "photoID": "M15",
    "gender": "M",
    "username": "Dexter O.",
    "cityState": "Fort Worth, TX",
    "numFriends": 201,
    "numReviews": 4,
    "numPhotos": 5,
    "date": "12/27/14",
    "numUseful": 0,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 1,
    "reviewScore": 4,
    "reviewText": "the past three months have been a wonderful blur ive never learned so much so quickly its incredible what the team at hack reactor have put together"
  },
  {
    "id": 84,
    "photoID": "M16",
    "gender": "M",
    "username": "Mitchell P.",
    "cityState": "Fresno, CA",
    "numFriends": 16,
    "numReviews": 1,
    "numPhotos": 52,
    "date": "1/19/15",
    "numUseful": 0,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 2,
    "reviewScore": 4,
    "reviewText": "furthermore i was pleasantly shocked by the level of support hack reactor gives its graduates after finishing there are whole teams dedicated to supporting grads in job search and the alumni network is incredibly strong with contacts at every major tech company in the bay area"
  },
  {
    "id": 41,
    "photoID": "M17",
    "gender": "M",
    "username": "Dawson Q.",
    "cityState": "Lexington, KY",
    "numFriends": 0,
    "numReviews": 5,
    "numPhotos": 34,
    "date": "7/8/15",
    "numUseful": 2,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 5,
    "reviewScore": 4,
    "reviewText": "as with any fast moving startup things change quickly hack reactor is scaling up fast and there are some minor pain points there wasnt perhaps as much contact time with senior industry veterans as id have hoped but it didnt seem to have an impact on what i learned the curriculum is rock solid"
  },
  {
    "id": 1,
    "photoID": "M18",
    "gender": "M",
    "username": "Grayson R.",
    "cityState": "St. Louis, MO",
    "numFriends": 75,
    "numReviews": 1,
    "numPhotos": 17,
    "date": "7/21/15",
    "numUseful": 1,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 2,
    "reviewScore": 4,
    "reviewText": "hack reactor holds its students to the highest of standards and i them hence four stars having said that i would certainly recommend the program to any of my friends who wanted to break into software engineering by far the most innovative and effective educational experience ive come across"
  },
  {
    "id": 37,
    "photoID": "M19",
    "gender": "M",
    "username": "Nicolas S.",
    "cityState": "Colorado Springs, CO",
    "numFriends": 0,
    "numReviews": 12,
    "numPhotos": 0,
    "date": "11/9/15",
    "numUseful": 2,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 4,
    "reviewScore": 5,
    "reviewText": "some intelligence determination and a sizable debt hire me at hack reactor finding someone who cares about your progress as a student is as simple as turning to the student next to you"
  },
  {
    "id": 30,
    "photoID": "M20",
    "gender": "M",
    "username": "Cason T.",
    "cityState": "Greensboro, NC",
    "numFriends": 77,
    "numReviews": 5,
    "numPhotos": 6,
    "date": "12/5/15",
    "numUseful": 0,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 3,
    "reviewScore": 5,
    "reviewText": "the program itself is intense yes but how else would you expect to learn an incredible amount of material in such a short amount of time the curriculum is constantly mutating as to keep its position as the number one bootcamp in javascript and primarily stay up to date with recent technologies furthermore you learn what really goes on in the industry how to work in that environment work well with other people and be successful at it"
  },
  {
    "id": 90,
    "photoID": "M21",
    "gender": "M",
    "username": "Zain U.",
    "cityState": "Aurora, CO",
    "numFriends": 21,
    "numReviews": 12,
    "numPhotos": 22,
    "date": "1/19/16",
    "numUseful": 5,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 7,
    "reviewScore": 5,
    "reviewText": "is it expensive at near 18k plus living costs in one of the most expensive cities in the world yes is it worth it absolutely"
  },
  {
    "id": 5,
    "photoID": "M22",
    "gender": "M",
    "username": "Deangelo V.",
    "cityState": "Portland, OR",
    "numFriends": 161,
    "numReviews": 12,
    "numPhotos": 10,
    "date": "3/24/16",
    "numUseful": 3,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 5,
    "reviewScore": 5,
    "reviewText": "is it intense / a lot of work at a minimum of 66 hours a week for 12 weeks it really is be prepared to lose touch with your friends and family for a while but tell them how stoked you are to be doing this amazing thing"
  },
  {
    "id": 31,
    "photoID": "M23",
    "gender": "M",
    "username": "Dangelo W.",
    "cityState": "Buffalo, NY",
    "numFriends": 4,
    "numReviews": 2,
    "numPhotos": 6,
    "date": "3/26/16",
    "numUseful": 4,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 5,
    "reviewScore": 5,
    "reviewText": "does it give you the skills you need yes you will come out confident in your abilities to work with databases frontend backend authentication frameworks algorithms datastructures the list goes on"
  },
  {
    "id": 15,
    "photoID": "M24",
    "gender": "M",
    "username": "Kieran X.",
    "cityState": "Omaha, NE",
    "numFriends": 22,
    "numReviews": 7,
    "numPhotos": 15,
    "date": "4/7/16",
    "numUseful": 5,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 5,
    "reviewScore": 5,
    "reviewText": "what they really ace in doing is their ability to teach students how to learn and pick up new technologies quickly if you complete this program and someone asks you if you can work in some foreign language / framework youve never heard of youll say no but i can learn it in no time and that is absolutely true"
  },
  {
    "id": 11,
    "photoID": "M25",
    "gender": "M",
    "username": "Emery Y.",
    "cityState": "Corpus Christi, TX",
    "numFriends": 43,
    "numReviews": 1,
    "numPhotos": 106,
    "date": "9/2/16",
    "numUseful": 5,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 8,
    "reviewScore": 5,
    "reviewText": "hack reactor was probably one of the most intense and rewarding educational experiences ive ever had its pretty crazy how much you can learn in just 13 weeks when i was looking for software engineering accelerators to apply to i was astounded by the overwhelmingly positive reviews written about hack reactor upon further investigation i also discovered that hack reactor had a pretty high admissions bar to me the high admissions bar pretty much provided me assurance that i could work with intelligent peers"
  },
  {
    "id": 16,
    "photoID": "M26",
    "gender": "M",
    "username": "Kale Z.",
    "cityState": "Sacramento, CA",
    "numFriends": 0,
    "numReviews": 2,
    "numPhotos": 68,
    "date": "9/15/16",
    "numUseful": 0,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 2,
    "reviewScore": 5,
    "reviewText": "the curriculum was amazing i felt like i was in a situation where i was constantly uncomfortable with the pace of the class but never uncomfortable enough to want to call it quits as you start getting comfortable with the unknown hack reactor will throw you into the project period where you really start getting uncomfortable and learn how to become an autonomous software engineer for me personally i thought that the project period was an invaluable part of hack reactors curriculum"
  },
  {
    "id": 42,
    "photoID": "M27",
    "gender": "M",
    "username": "Zander A.",
    "cityState": "Long Beach, CA",
    "numFriends": 174,
    "numReviews": 6,
    "numPhotos": 2,
    "date": "11/14/16",
    "numUseful": 0,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 1,
    "reviewScore": 5,
    "reviewText": "at the end of it all youll pretty much become an expert at all things javascript and have the confidence to solve a plethora of engineering challenges if youre considering a software engineering accelerator i highly suggest choosing hack reactor if you can get in"
  },
  {
    "id": 85,
    "photoID": "M28",
    "gender": "M",
    "username": "Beckham B.",
    "cityState": "Kansas City, MO",
    "numFriends": 50,
    "numReviews": 9,
    "numPhotos": 0,
    "date": "11/16/16",
    "numUseful": 8,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 9,
    "reviewScore": 5,
    "reviewText": "bottom line : hack reactor trains you how to be a real software engineer instead of coming out of your education with debt and a piece of paper you leave hack reactor with real world skills and real world accomplishments at hack reactor youre not playing in the sandbox youre put in the ocean and you learn to swim from there the invested time and effort is tremendous but thats what real learning is"
  },
  {
    "id": 61,
    "photoID": "M29",
    "gender": "M",
    "username": "Dillon C.",
    "cityState": "Milwaukee, WI",
    "numFriends": 17,
    "numReviews": 9,
    "numPhotos": 75,
    "date": "3/21/17",
    "numUseful": 0,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 1,
    "reviewScore": 5,
    "reviewText": "i applied to many immersive programming courses and selected hack reactor frankly because their reputation was very positive with my friends who are already working in tech hack reactor is known for producing very competent software engineers"
  },
  {
    "id": 14,
    "photoID": "M30",
    "gender": "M",
    "username": "Blaze D.",
    "cityState": "Arlington, VA",
    "numFriends": 188,
    "numReviews": 4,
    "numPhotos": 9,
    "date": "9/3/17",
    "numUseful": 6,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 7,
    "reviewScore": 5,
    "reviewText": "the program is split into two sections a very intense first 6 weeks full of back to back 2 day sprints and a more freeform second 6 weeks thats more selfmanaged and for working on projects with groups hack reactor strikes a great balance between structured class work and practical project experience"
  },
  {
    "id": 40,
    "photoID": "M31",
    "gender": "M",
    "username": "Jorden E.",
    "cityState": "Washington, DC",
    "numFriends": 0,
    "numReviews": 7,
    "numPhotos": 20,
    "date": "3/27/18",
    "numUseful": 10,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 11,
    "reviewScore": 5,
    "reviewText": "what really made the experience for me was the people i met you spend all day 6 days a week with your cohort and you will make some really incredible friendships in summary hack reactor was the right choice for me and i am really happy with the results of the program"
  },
  {
    "id": 62,
    "photoID": "M32",
    "gender": "M",
    "username": "Owen F.",
    "cityState": "Hialeah, Florida",
    "numFriends": 66,
    "numReviews": 2,
    "numPhotos": 101,
    "date": "5/10/18",
    "numUseful": 8,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 11,
    "reviewScore": 5,
    "reviewText": "as other reviews have suggested hack reactor was one of the most intense experiences of my life 13 weeks flew by and i learned more here than i ever thought i could"
  },
  {
    "id": 45,
    "photoID": "M33",
    "gender": "M",
    "username": "Pierre G.",
    "cityState": "Oklahoma Cty, OK",
    "numFriends": 116,
    "numReviews": 1,
    "numPhotos": 1,
    "date": "6/25/18",
    "numUseful": 4,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 7,
    "reviewScore": 5,
    "reviewText": "i was rather skeptical of hack reactor when i first heard about it i couldnt believe that you could learn to be a software engineer within 13 weeks however after reading positive articles and many blogs on the hack reactor experience i bit the bullet and i am very glad i did"
  },
  {
    "id": 29,
    "photoID": "M34",
    "gender": "M",
    "username": "Beckett H.",
    "cityState": "San Jose, CA",
    "numFriends": 0,
    "numReviews": 11,
    "numPhotos": 55,
    "date": "7/28/18",
    "numUseful": 7,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 10,
    "reviewScore": 5,
    "reviewText": "hack reactor teaches you a lot of things about computer science focused exclusively in javascript in a short amount of time but you need to have the right attitude going into this theres no magic happening here if youre in it for the salary expectations as opposed to a love of programming hack reactor wont transform you into a highly paid software engineer however hack reactor does place you in an environment where you have the resources and guidance needed to make the most out of your time i occasionally worked for over 12 hours a day but it never felt like work"
  },
  {
    "id": 9,
    "photoID": "M35",
    "gender": "M",
    "username": "Elias I.",
    "cityState": "Lubbock, TX",
    "numFriends": 0,
    "numReviews": 2,
    "numPhotos": 3,
    "date": "8/5/18",
    "numUseful": 9,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 9,
    "reviewScore": 5,
    "reviewText": "also the curriculum carefully transitions from teaching you a lot of material to teaching you how to teach yourself by the end of hack reactor i was able to teach myself new frameworks almost as quickly as the carefully crafted lessons for the frameworks that hack reactor taught us"
  },
  {
    "id": 43,
    "photoID": "M36",
    "gender": "M",
    "username": "Rex J.",
    "cityState": "Raleigh, NC",
    "numFriends": 77,
    "numReviews": 10,
    "numPhotos": 120,
    "date": "1/13/19",
    "numUseful": 2,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 2,
    "reviewScore": 5,
    "reviewText": "if youre looking into a software engineering career accelerator you should go to hack reactor if you can get into hack reactor not for the faint of heart definitely one of the most intense 13 wks of my life"
  },
  {
    "id": 76,
    "photoID": "M37",
    "gender": "M",
    "username": "Lawson K.",
    "cityState": "Denver, CO",
    "numFriends": 41,
    "numReviews": 5,
    "numPhotos": 71,
    "date": "4/28/19",
    "numUseful": 7,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 8,
    "reviewScore": 5,
    "reviewText": "its a rare opportunity to find yourself so intellectually stimulated and surrounded by so many driven and intelligent people with similar goals as you in one place my colleagues include those who graduated from mit stanford and brown just to name a few i was constantly challenged and inspired to collaborate and build amazing projects with them"
  },
  {
    "id": 32,
    "photoID": "M38",
    "gender": "M",
    "username": "Marshall L.",
    "cityState": "Albuquerque, NM",
    "numFriends": 0,
    "numReviews": 10,
    "numPhotos": 3,
    "date": "8/10/13",
    "numUseful": 5,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 6,
    "reviewScore": 5,
    "reviewText": "hack reactor doesnt just teach you javascript and the hottest newest development frameworks yes they teach data structures algorithms time complexity computer science concepts fullstack development and more however the most valuable skill you will develop is problem solving you learn to analyze problems identify constraints pick the right tools and seek mentorship necessary to achieve your goals"
  },
  {
    "id": 68,
    "photoID": "M39",
    "gender": "M",
    "username": "Wayne M.",
    "cityState": "Madison, WI",
    "numFriends": 53,
    "numReviews": 4,
    "numPhotos": 2,
    "date": "9/10/13",
    "numUseful": 9,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 11,
    "reviewScore": 5,
    "reviewText": "hack reactor is a place where great minds are turned into great web developers they teach you all about the most common computer science techniques and give you a healthy understanding of the full stack using primarily javascript the only real criticism i have is that they should go in depth into more languages especially on the backend"
  },
  {
    "id": 6,
    "photoID": "M40",
    "gender": "M",
    "username": "Larry N.",
    "cityState": "Bakersfield, CA",
    "numFriends": 147,
    "numReviews": 1,
    "numPhotos": 101,
    "date": "1/20/14",
    "numUseful": 7,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 9,
    "reviewScore": 5,
    "reviewText": "but what they teach on paper isnt too important compared to the skills they give you to master any language i would recommend this program to anyone who wants to be a software engineer and is up to the challenge"
  },
  {
    "id": 19,
    "photoID": "M41",
    "gender": "M",
    "username": "Tate O.",
    "cityState": "Norfolk, VA",
    "numFriends": 0,
    "numReviews": 6,
    "numPhotos": 97,
    "date": "3/8/14",
    "numUseful": 9,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 10,
    "reviewScore": 5,
    "reviewText": "i expected to learn how to build apps and hr helped me grasped a solid understanding of web development fundamentals latest web development technologies frameworks i expected to be a good software engineer and hr went beyond my expectation i learned team dynamics project management presentation skills negotiation skills and best of all formed some of the strongest bondings with friends i know would be lifelong friends thank you hack reactor to close : i accepted an offer after three weeks of graduation starting a new job as a frontend developer next Monday 99% job success is solid"
  },
  {
    "id": 47,
    "photoID": "M42",
    "gender": "M",
    "username": "Brogan P.",
    "cityState": "Tucson, AZ",
    "numFriends": 0,
    "numReviews": 1,
    "numPhotos": 2,
    "date": "6/30/14",
    "numUseful": 7,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 8,
    "reviewScore": 5,
    "reviewText": "best decision of my life all the hype is true i believe hack reactor is the pioneer for what will soon become the norm in education it was an entire college experience and then some crushed into 6 months including precourse work it was miles above anything i experienced while getting my undergraduate degree and after leaving i feel more confident in my abilities than i thought i could what makes hack reactor so great are the hearts they have the best minds on changing the education industry but more importantly they have the best hearts on it hack reactor is not for you if you feel like you just want to get in and get out the best way to be successful is coming in with an open mind and love for being part of a team just amazing"
  },
  {
    "id": 7,
    "photoID": "M43",
    "gender": "M",
    "username": "Kelvin Q.",
    "cityState": "Dallas, TX",
    "numFriends": 23,
    "numReviews": 3,
    "numPhotos": 74,
    "date": "11/21/14",
    "numUseful": 7,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 7,
    "reviewScore": 5,
    "reviewText": "i literally want to copy and paste everyone elses reviews of this place into my own i think it says a lot that the experience is universally transformative impactful and meaningful no matter what walk of life you are coming from to attend at hack reactor there are teams of people dedicated to your success and the quality of those teams are worth every penny of tuition perhaps more important than the external support you receive is the fact that the program trains you to be a self-supporting engineer i feel like i have the tools i need to figure out any problem and that is an invaluable feeling"
  },
  {
    "id": 53,
    "photoID": "M44",
    "gender": "M",
    "username": "Makhi R.",
    "cityState": "New Orleans, LA",
    "numFriends": 0,
    "numReviews": 1,
    "numPhotos": 48,
    "date": "11/29/14",
    "numUseful": 6,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 8,
    "reviewScore": 5,
    "reviewText": "hack reactor is an incredible place to learn to code and to grow as an individual i consider myself very fortunate to have had the opportunity to be a student and would highly recommend it to anyone that is accepted ive listed a few reasons below"
  },
  {
    "id": 23,
    "photoID": "M45",
    "gender": "M",
    "username": "Andres S.",
    "cityState": "San Antonio, TX",
    "numFriends": 35,
    "numReviews": 3,
    "numPhotos": 40,
    "date": "2/2/15",
    "numUseful": 6,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 7,
    "reviewScore": 5,
    "reviewText": "become a capable software engineer over twenty weeks 8 in precourse 12 onsite i grew from coding static webpages in html / css to contributing to codebases with single page app functionality built using libraries like backbone react and angular nodejs express servers and mysql postgres databases"
  },
  {
    "id": 75,
    "photoID": "M46",
    "gender": "M",
    "username": "Pranav T.",
    "cityState": "Newark, NJ",
    "numFriends": 221,
    "numReviews": 10,
    "numPhotos": 105,
    "date": "12/17/15",
    "numUseful": 7,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 7,
    "reviewScore": 5,
    "reviewText": "empower yourself to solve problems hack reactors philosophy is to turn students into autonomous learners and they do a great job facilitating this mindset i realized that i am capable of learning anything and that by taking personal responsibility for my learning i could accelerate my growth and overcome technical challenges"
  },
  {
    "id": 74,
    "photoID": "M47",
    "gender": "M",
    "username": "Tristan U.",
    "cityState": "Tampa, FL",
    "numFriends": 44,
    "numReviews": 6,
    "numPhotos": 7,
    "date": "1/21/16",
    "numUseful": 5,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 8,
    "reviewScore": 5,
    "reviewText": "surround yourself with brilliant and motivated people hack reactors admissions process is rigorous and the end result is that all of my cohort mates were brilliant motivated great people to be around"
  },
  {
    "id": 100,
    "photoID": "M48",
    "gender": "M",
    "username": "Carsen V.",
    "cityState": "Honolulu, HI",
    "numFriends": 16,
    "numReviews": 10,
    "numPhotos": 51,
    "date": "5/6/16",
    "numUseful": 10,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 10,
    "reviewScore": 5,
    "reviewText": "attend school at a place that truly invests in you the cost of the program is justified in longer hours 6 days / week 11 hours / day incredible job search support precourse mentoring and alumni career services into perpetuity"
  },
  {
    "id": 50,
    "photoID": "M49",
    "gender": "M",
    "username": "Ruben W.",
    "cityState": "Cincinnati, OH",
    "numFriends": 130,
    "numReviews": 9,
    "numPhotos": 103,
    "date": "5/16/16",
    "numUseful": 9,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 10,
    "reviewScore": 5,
    "reviewText": "you also end up learning a lot about teaching from the instructors the structure of the course and the way its rapidly iterated towards the end youre coached through creating your new resume curating your online presence and getting ready for the job search the staff is insanely committed to doing everything in their power to help you find the right job"
  },
  {
    "id": 38,
    "photoID": "M50",
    "gender": "M",
    "username": "Phillip X.",
    "cityState": "Reno, NV",
    "numFriends": 0,
    "numReviews": 11,
    "numPhotos": 10,
    "date": "6/4/16",
    "numUseful": 2,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 5,
    "reviewScore": 5,
    "reviewText": "i could ramble on about hack reactor for a long time but i think thats enough for now if youre serious about leveling up your skills quickly and you have the resources to attend just do it"
  },
  {
    "id": 89,
    "photoID": "F01",
    "gender": "F",
    "username": "Allyson Y.",
    "cityState": "Huntington, NY",
    "numFriends": 218,
    "numReviews": 6,
    "numPhotos": 108,
    "date": "8/8/16",
    "numUseful": 5,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 6,
    "reviewScore": 1,
    "reviewText": "save before nothing discipline free the for the tuition fee precourse to the learning learning strategies are available to everyone internet it the above work on to think be for available to everyone the answers yourself withdrew that was learn from them other email point you this was really know of coding that is etc the technical is etc to mirror real world which is real is intended intended intended to real world my which are are are it it counselor yourself a week my they all and and trustworthy they they make sweet around the and too alumni too why why their you them to learn but a but but you have lots yourself could could of we the countless to come of own for free the instructors tell the learning tell the answers yourself by looking them up in in forums discussing with other coders / students of that you have found etc this have counselor check which was it the the countless counselor"
  },
  {
    "id": 25,
    "photoID": "F02",
    "gender": "F",
    "username": "Kathy Z.",
    "cityState": "Chesapeake, VA",
    "numFriends": 0,
    "numReviews": 9,
    "numPhotos": 60,
    "date": "1/15/17",
    "numUseful": 4,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 5,
    "reviewScore": 1,
    "reviewText": "was is you can into reactor for own tuition fee and cover any all were if you will learn to takes have of extra assessment so so hack reactors withdrew tuition the must be for"
  },
  {
    "id": 67,
    "photoID": "F03",
    "gender": "F",
    "username": "Virginia A.",
    "cityState": "Baltimore, MD",
    "numFriends": 178,
    "numReviews": 2,
    "numPhotos": 22,
    "date": "1/28/17",
    "numUseful": 0,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 0,
    "reviewScore": 1,
    "reviewText": "reactor covers makes with that is you can for insane tuition for sense sense is you learning for you have to have the instructors is the answers are obscene long counselor to respond world which messages do academy respond it sorry had a a do not and\nterrible you have considerably content to yourself on the above learning learning strategies are to code the countless internet so so hack reactors fee must for instruction itself itself"
  },
  {
    "id": 33,
    "photoID": "F04",
    "gender": "F",
    "username": "Imani B.",
    "cityState": "Fort Wayne, IN",
    "numFriends": 93,
    "numReviews": 1,
    "numPhotos": 1,
    "date": "4/29/17",
    "numUseful": 3,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 3,
    "reviewScore": 1,
    "reviewText": "you have which was you yourself of yourself no family to fee were above learning strategies are no to assessment withdrew internet so so hack reactors fee and seems like a bunch of we your to your get the did counselor is the to ive is precourse that supposed to come the real is intended to mirror have world scenarios is which yourself but leaves me wondering - what for do exactly you get for the tuition all of the above luck learning strategies are available to everyone on the internet so hack reactors fee must be for the instruction itself"
  },
  {
    "id": 92,
    "photoID": "F05",
    "gender": "F",
    "username": "Lauryn C.",
    "cityState": "Las Vegas, NV",
    "numFriends": 203,
    "numReviews": 3,
    "numPhotos": 5,
    "date": "5/7/17",
    "numUseful": 10,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 10,
    "reviewScore": 1,
    "reviewText": "problem with that is you can find better instructional videos on youtube that cover any and all topics hack reactor covers so again what the hell is the insane tuition for"
  },
  {
    "id": 48,
    "photoID": "F06",
    "gender": "F",
    "username": "Salma D.",
    "cityState": "Anchorage, AK",
    "numFriends": 0,
    "numReviews": 1,
    "numPhotos": 8,
    "date": "10/5/17",
    "numUseful": 6,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 7,
    "reviewScore": 2,
    "reviewText": "the building concierge was super helpful apologizing to me and 1 other person because hack reactor forgot to block out their tour calendar he enlisted another handy man to help get us back to our cars"
  },
  {
    "id": 97,
    "photoID": "F07",
    "gender": "F",
    "username": "Jacey E.",
    "cityState": "San Francisco, CA",
    "numFriends": 105,
    "numReviews": 10,
    "numPhotos": 0,
    "date": "6/12/18",
    "numUseful": 5,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 5,
    "reviewScore": 2,
    "reviewText": "job placement is about 15 percent for cohort graduated 3 months ago from time of this post and about 10 percent for cohort graduated 1 month ago those who found jobs have previous computer science experience as well so job market is rough for the regular students who are already bright and sharp since it is about a 35 percent acceptance rate just to get into hr"
  },
  {
    "id": 59,
    "photoID": "F08",
    "gender": "F",
    "username": "Patricia F.",
    "cityState": "Montgomery, AL",
    "numFriends": 151,
    "numReviews": 8,
    "numPhotos": 105,
    "date": "8/26/18",
    "numUseful": 1,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 4,
    "reviewScore": 2,
    "reviewText": "and you want me to give you 20000 dollars ? i think not i selected coding dojo instead"
  },
  {
    "id": 55,
    "photoID": "F09",
    "gender": "F",
    "username": "Lorelei G.",
    "cityState": "Oakland, CA",
    "numFriends": 0,
    "numReviews": 7,
    "numPhotos": 30,
    "date": "10/7/18",
    "numUseful": 3,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 5,
    "reviewScore": 3,
    "reviewText": "at the end of 6 weeks students are required to pass a 6 hour exam some of the questions on this exam were repeated from the earlier weekly assessment i copied and pasted my answer to one question from my weekly assessment for the exam out of 21 students in my class 1 in 3 students also did the exact same thing yet my class lead only singled me out and tried to have me kicked out of the program for this it is a shame that program with such a high reputation would have it tarnished by the personal vindictive nature of our class lead the other third of the class that did the exact same thing i did were not treated the same way not sure what drives a person to be so petty"
  },
  {
    "id": 2,
    "photoID": "F10",
    "gender": "F",
    "username": "Jaliyah H.",
    "cityState": "North Hempstead, NY",
    "numFriends": 282,
    "numReviews": 4,
    "numPhotos": 77,
    "date": "11/14/18",
    "numUseful": 6,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 7,
    "reviewScore": 3,
    "reviewText": "there are only 2 negatives about the program with the remote program the training is done online and you are watching recordings of actual class sessions from the onsite program that were filmed 6 months prior in some of the videos the instructor is talking about what is being shown on the screen or on his computer but this was not recorded so you miss out on this material other times students ask questions but since they are not near a microphone you will not hear the question but you will hear the instructors answer"
  },
  {
    "id": 56,
    "photoID": "F11",
    "gender": "F",
    "username": "Heather I.",
    "cityState": "Anaheim, CA",
    "numFriends": 0,
    "numReviews": 7,
    "numPhotos": 2,
    "date": "2/4/19",
    "numUseful": 6,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 7,
    "reviewScore": 3,
    "reviewText": "this is mostly due to what appears to be a severe lack in junior level and midlevel jobs in the la area but it also proves that nowadays going to an expensive coding bootcamp will not increase your chances of getting a job they do well to tell you that when you sign up dont think youre guatenteed a job and in fact sometimes they tell you not to even mention that you ever attended a coding bootcamp employers are weary of bootcampers now"
  },
  {
    "id": 80,
    "photoID": "F12",
    "gender": "F",
    "username": "Raven J.",
    "cityState": "Scottsdale, AZ",
    "numFriends": 44,
    "numReviews": 2,
    "numPhotos": 43,
    "date": "3/25/19",
    "numUseful": 10,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 12,
    "reviewScore": 3,
    "reviewText": "with another 20 engineers being pumped out every 3 months the market for fresh engineers seems to be pretty much at capacity in la it seems to be more about who you already know that what your skillset is most of the smartest kids still dont have jobs"
  },
  {
    "id": 95,
    "photoID": "F13",
    "gender": "F",
    "username": "Cierra K.",
    "cityState": "Columbus, OH",
    "numFriends": 217,
    "numReviews": 12,
    "numPhotos": 43,
    "date": "3/17/14",
    "numUseful": 5,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 5,
    "reviewScore": 3,
    "reviewText": "before i attended hack reactor my main problem was simply managing to code through projects autonomously meaning if i ran into a big enough problem i had no idea where to turn to solve it after hack reactor i can say that i was mostly autonomous and could finally start to figure out tough issues by myself hack reactor gave me confidence but unfortunately it seems like the resume is what counts in this game no job experience means no job for this reason many people in the cohorts i was familiar with are now turning to searching for unpaid internships"
  },
  {
    "id": 10,
    "photoID": "F14",
    "gender": "F",
    "username": "Lillian L.",
    "cityState": "Wichita, KS",
    "numFriends": 231,
    "numReviews": 6,
    "numPhotos": 88,
    "date": "4/23/14",
    "numUseful": 2,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 5,
    "reviewScore": 4,
    "reviewText": "be mentally prepared for the job hunt which in and of itself is like another bootcamp of sorts its a mentally and emotionally challenging process phone screens coding challenges technical interviews and the like dont expect to graduate from hack reactor and just have job offers thrown at you a select few graduates will get lucky youre going to need to work for it but know that in the end itll all be alright all the previous graduates have done well for themselves"
  },
  {
    "id": 13,
    "photoID": "F15",
    "gender": "F",
    "username": "Lexi M.",
    "cityState": "St. Petersburg, FL",
    "numFriends": 6,
    "numReviews": 1,
    "numPhotos": 72,
    "date": "6/17/14",
    "numUseful": 8,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 9,
    "reviewScore": 4,
    "reviewText": "that being said hack reactor has far exceeded my expectation in many ways"
  },
  {
    "id": 94,
    "photoID": "F16",
    "gender": "F",
    "username": "Luz N.",
    "cityState": "Atlanta, GA",
    "numFriends": 4,
    "numReviews": 8,
    "numPhotos": 49,
    "date": "9/3/14",
    "numUseful": 5,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 6,
    "reviewScore": 4,
    "reviewText": "i was skeptical about whether it is possible to learn the technical skills in 3 month i was an engineering undergrad and no technical subject too less than 3 month to learn let a lone modern web development which could have been easily a year or two curriculum at an uni the jam packed schedule that hack reactor brings drills the necessary knowledge into its students"
  },
  {
    "id": 99,
    "photoID": "F17",
    "gender": "F",
    "username": "Kirsten O.",
    "cityState": "Akron, OH",
    "numFriends": 48,
    "numReviews": 4,
    "numPhotos": 97,
    "date": "12/2/14",
    "numUseful": 5,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 5,
    "reviewScore": 4,
    "reviewText": "my classmates were very bright and capable which made the course work as well as offwork activities very enjoyable"
  },
  {
    "id": 79,
    "photoID": "F18",
    "gender": "F",
    "username": "Carina P.",
    "cityState": "Minneapolis, MN",
    "numFriends": 2,
    "numReviews": 9,
    "numPhotos": 16,
    "date": "12/8/14",
    "numUseful": 1,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 1,
    "reviewScore": 4,
    "reviewText": "i find their concept of continuously improving and tweaking their curriculum fascinating and it is what education should have been at all learning institutions"
  },
  {
    "id": 44,
    "photoID": "F19",
    "gender": "F",
    "username": "Sadie Q.",
    "cityState": "Baton Rouge, LA",
    "numFriends": 6,
    "numReviews": 2,
    "numPhotos": 40,
    "date": "1/25/15",
    "numUseful": 3,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 5,
    "reviewScore": 5,
    "reviewText": "hack reactor is like the part in groundhog day where bill murray learns to play the piano it is a time warp i blink and the day is over i look back and it feels like weve been building awesome projects and picking up skills on the fly for years"
  },
  {
    "id": 24,
    "photoID": "F20",
    "gender": "F",
    "username": "Briley R.",
    "cityState": "Virginia Beach, VA",
    "numFriends": 0,
    "numReviews": 10,
    "numPhotos": 120,
    "date": "3/13/15",
    "numUseful": 4,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 4,
    "reviewScore": 5,
    "reviewText": "hack reactor isnt perfect and doesnt try to be perfect this desire to constantly improve by what they call rapid iteration education is one of their greatest strengths the staff is completely ready to uproot something theyve been doing at hack reactor since it was founded and replace it with something that will improve the quality of our education i saw this happen multiple times during my cohort and it was always in our best interest"
  },
  {
    "id": 88,
    "photoID": "F21",
    "gender": "F",
    "username": "Brylee S.",
    "cityState": "Birmingham, AL",
    "numFriends": 167,
    "numReviews": 1,
    "numPhotos": 28,
    "date": "4/17/15",
    "numUseful": 2,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 2,
    "reviewScore": 5,
    "reviewText": "the entire staff cares deeply about each student and it shows from day 1 there are resources available to help with the technical and emotional challenges of the intense 3 month gauntlet they ask us to bring our best technical and personal every single day and in return they do the same"
  },
  {
    "id": 63,
    "photoID": "F22",
    "gender": "F",
    "username": "Naima T.",
    "cityState": "New York, NY",
    "numFriends": 97,
    "numReviews": 8,
    "numPhotos": 18,
    "date": "12/11/15",
    "numUseful": 2,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 5,
    "reviewScore": 5,
    "reviewText": "in addition to learning cs fundamentals several mvc frameworks functional programming debugging full stack development the list goes on one of the greatest skills we learn is autonomy the ability to be given a task or come up with one that requires using technologies weve never seen before and build it to break down understand research learn plan build and optimize our way to a solution it is a profound skill that allows us to be given a task in any language or framework and confidently say great ill spin it up"
  },
  {
    "id": 21,
    "photoID": "F23",
    "gender": "F",
    "username": "Hailee U.",
    "cityState": "El Paso, TX",
    "numFriends": 0,
    "numReviews": 8,
    "numPhotos": 46,
    "date": "4/2/16",
    "numUseful": 4,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 6,
    "reviewScore": 5,
    "reviewText": "my group of peers at hack reactor are some of the most bright optimistic caring and fun people ive ever met they are people that i am honored to have spent 3 months giving everything i have working late nights shoulder to shoulder with together hack reactor emphasizes soft skills in addition to the technical skills and it allows for immense personal and emotional growth if one is willing to put in the effort"
  },
  {
    "id": 93,
    "photoID": "F24",
    "gender": "F",
    "username": "Eve V.",
    "cityState": "Arlington, TX",
    "numFriends": 0,
    "numReviews": 5,
    "numPhotos": 8,
    "date": "8/7/16",
    "numUseful": 7,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 8,
    "reviewScore": 5,
    "reviewText": "hack reactor is bigger than its advanced software engineering immersive program it is building a new form of education it requires 6 days / week of 11 + hour days and it works it simply works its outrageously effective its been said before and remains to be true : if you can get into hack reactor you should go to hack reactor"
  },
  {
    "id": 87,
    "photoID": "F25",
    "gender": "F",
    "username": "Neveah W.",
    "cityState": "Modesto, CA",
    "numFriends": 191,
    "numReviews": 4,
    "numPhotos": 97,
    "date": "8/18/16",
    "numUseful": 2,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 2,
    "reviewScore": 5,
    "reviewText": "i think a common thought process for anyone seeking a coding bootcamp is to start out interested but skeptical this wavelength continues until a while after completion when it finally sinks in that they were telling the truth however hack reactor manages to ease this skepticism almost immediately"
  },
  {
    "id": 35,
    "photoID": "F26",
    "gender": "F",
    "username": "Rowan X.",
    "cityState": "San Diego, CA",
    "numFriends": 13,
    "numReviews": 2,
    "numPhotos": 3,
    "date": "10/16/16",
    "numUseful": 7,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 8,
    "reviewScore": 5,
    "reviewText": "this place thrives on the amazing community it is so successful in building the people that come in out and frequent hr are passionate fun hardworking and absolutely unique most everyone i met came from a different walk of life such as a forklift driver bartender students in college people with cs degrees people without degrees women and men ages 18 through mid50s and from all over the world"
  },
  {
    "id": 73,
    "photoID": "F27",
    "gender": "F",
    "username": "Eden Y.",
    "cityState": "Chula Vista, CA",
    "numFriends": 105,
    "numReviews": 12,
    "numPhotos": 0,
    "date": "1/10/17",
    "numUseful": 5,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 7,
    "reviewScore": 5,
    "reviewText": "they genuinely care about the students that come to the program this is what sets hack reactor apart from any other paid learning environment ive participated in college these days feels more and more like a business the only point of which attending is to come out the other side with a piece of paper that proclaims i have some intelligence determination and a sizable debt hire me at hack reactor finding someone who cares about your progress as a student is as simple as turning to the student next to you"
  },
  {
    "id": 71,
    "photoID": "F28",
    "gender": "F",
    "username": "Savanna Z.",
    "cityState": "Garland, TX",
    "numFriends": 2,
    "numReviews": 4,
    "numPhotos": 59,
    "date": "3/16/17",
    "numUseful": 7,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 8,
    "reviewScore": 5,
    "reviewText": "amount of material in such a short amount of time the curriculum is constantly mutating as to keep its position as the number one bootcamp in javascript and primarily stay uptodate with recent technologies furthermore you learn what really goes on in the industry how to work in that environment work well with other people and be successful at it\nthe bottom line"
  },
  {
    "id": 46,
    "photoID": "F29",
    "gender": "F",
    "username": "Mina A.",
    "cityState": "Philadelphia, PA",
    "numFriends": 6,
    "numReviews": 8,
    "numPhotos": 7,
    "date": "6/28/17",
    "numUseful": 6,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 9,
    "reviewScore": 5,
    "reviewText": "at the end of it all youll pretty much become an expert at all things javascript and have the confidence to solve a plethora of engineering challenges if youre considering a software engineering accelerator i highly suggest choosing hack reactor if you can get in"
  },
  {
    "id": 12,
    "photoID": "F30",
    "gender": "F",
    "username": "Laylah B.",
    "cityState": "Nashville, TN",
    "numFriends": 158,
    "numReviews": 3,
    "numPhotos": 112,
    "date": "8/13/17",
    "numUseful": 1,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 2,
    "reviewScore": 5,
    "reviewText": "i was rather skeptical of hack reactor when i first heard about it i couldnt believe that you could learn to be a software engineer within 13 weeks however after reading positive articles and many blogs on the hack reactor experience i bit the bullet and i am very glad i did hack reactor teaches you a lot of things"
  },
  {
    "id": 82,
    "photoID": "F31",
    "gender": "F",
    "username": "Meadow C.",
    "cityState": "Riverside, CA",
    "numFriends": 18,
    "numReviews": 6,
    "numPhotos": 32,
    "date": "3/2/18",
    "numUseful": 1,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 2,
    "reviewScore": 5,
    "reviewText": "what really made the experience for me was the people i met you spend all day 6 days a week with your cohort and you will make some really incredible friendships in summary hack reactor was the right choice for me and i am really happy with the results of the program"
  },
  {
    "id": 39,
    "photoID": "F32",
    "gender": "F",
    "username": "Amira D.",
    "cityState": "Orlando, FL",
    "numFriends": 255,
    "numReviews": 10,
    "numPhotos": 37,
    "date": "7/3/18",
    "numUseful": 2,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 3,
    "reviewScore": 5,
    "reviewText": "the program is split into two sections a very intense first 6 weeks full of backtoback 2 day sprints and a more freeform second 6 weeks thats more selfmanaged and for working on projects with groups hack reactor strikes a great balance between structured class work and practical project experience"
  },
  {
    "id": 8,
    "photoID": "F33",
    "gender": "F",
    "username": "Olive E.",
    "cityState": "Tulsa, OK",
    "numFriends": 51,
    "numReviews": 4,
    "numPhotos": 114,
    "date": "11/5/18",
    "numUseful": 1,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 4,
    "reviewScore": 5,
    "reviewText": "i applied to many immersive programming courses and selected hack reactor frankly because their reputation was very positive with my friends who are already working in tech hack reactor is known for producing very competent software engineers"
  },
  {
    "id": 49,
    "photoID": "F34",
    "gender": "F",
    "username": "Haleigh F.",
    "cityState": "Los Angeles, CA",
    "numFriends": 65,
    "numReviews": 12,
    "numPhotos": 8,
    "date": "3/21/19",
    "numUseful": 3,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 5,
    "reviewScore": 5,
    "reviewText": "bottom line : hack reactor trains you how to be a real software engineer instead of coming out of your education with debt and a piece of paper you leave hack reactor with real world skills and real world accomplishments at hack reactor youre not playing in the sandbox youre put in the ocean and you learn to swim from there the invested time and effort is tremendous but thats what real learning is"
  },
  {
    "id": 96,
    "photoID": "F35",
    "gender": "F",
    "username": "Jamya G.",
    "cityState": "Boston, MA",
    "numFriends": 8,
    "numReviews": 10,
    "numPhotos": 85,
    "date": "3/30/19",
    "numUseful": 8,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 9,
    "reviewScore": 5,
    "reviewText": "at the end of it all youll pretty much become an expert at all things javascript and have the confidence to solve a plethora of engineering challenges if youre considering a software engineering accelerator i highly suggest choosing hack reactor if you can get in"
  },
  {
    "id": 4,
    "photoID": "F36",
    "gender": "F",
    "username": "Carley H.",
    "cityState": "Jacksonville, FL",
    "numFriends": 38,
    "numReviews": 9,
    "numPhotos": 32,
    "date": "5/15/16",
    "numUseful": 3,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 4,
    "reviewScore": 5,
    "reviewText": "he curriculum was amazing i felt like i was in a situation where i was constantly uncomfortable with the pace of the class but never uncomfortable enough to want to call it quits as you start getting comfortable with the unknown hack reactor will throw you into the project period where you really start getting uncomfortable and learn how to become an autonomous software engineer for me personally i thought that the project period was an invaluable part of hack reactors curriculum"
  },
  {
    "id": 26,
    "photoID": "F37",
    "gender": "F",
    "username": "Myla I.",
    "cityState": "Durham, CA",
    "numFriends": 213,
    "numReviews": 2,
    "numPhotos": 23,
    "date": "9/22/16",
    "numUseful": 4,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 7,
    "reviewScore": 5,
    "reviewText": "hack reactor was probably one of the most intense and rewarding educational experiences ive ever had its pretty crazy how much you can learn in just 13 weeks when i was looking for software engineering accelerators to apply to i was astounded by the overwhelmingly positive reviews written about hack reactor upon further investigation i also discovered that hack reactor had a pretty high admissions bar to me the high admissions bar pretty much provided me assurance that i could work with intelligent peers"
  },
  {
    "id": 81,
    "photoID": "F38",
    "gender": "F",
    "username": "Belen J.",
    "cityState": "St. Paul, MN",
    "numFriends": 0,
    "numReviews": 1,
    "numPhotos": 62,
    "date": "9/27/16",
    "numUseful": 2,
    "numFunny": 2,
    "numCool": 0,
    "numVotes": 4,
    "reviewScore": 5,
    "reviewText": "what they really ace in doing is their ability to teach students how to learn and pick up new technologies quickly if you complete this program and someone asks you if you can work in some foreign language / framework youve never heard of youll say no but i can learn it in no time and that is absolutely true"
  },
  {
    "id": 51,
    "photoID": "F39",
    "gender": "F",
    "username": "Bailee K.",
    "cityState": "Miami, FL",
    "numFriends": 137,
    "numReviews": 4,
    "numPhotos": 30,
    "date": "11/27/16",
    "numUseful": 5,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 5,
    "reviewScore": 5,
    "reviewText": "does it give you the skills you need yes you will come out confident in your abilities to work with databases frontend backend authentication frameworks algorithms datas tructures the list goes on"
  },
  {
    "id": 18,
    "photoID": "F40",
    "gender": "F",
    "username": "Miya L.",
    "cityState": "Stockton, CA",
    "numFriends": 80,
    "numReviews": 4,
    "numPhotos": 48,
    "date": "2/5/17",
    "numUseful": 2,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 3,
    "reviewScore": 5,
    "reviewText": "this place thrives on the amazing community it is so successful in building the people that come in out and frequent hr are passionate fun hardworking and absolutely unique most everyone i met came from a different walk of life such as a forklift driver bartender students in college people with cs degrees people without degrees women and men ages 18 through mid50s and from all over the world"
  },
  {
    "id": 27,
    "photoID": "F41",
    "gender": "F",
    "username": "Natalie M.",
    "cityState": "Toledo, OH",
    "numFriends": 113,
    "numReviews": 10,
    "numPhotos": 28,
    "date": "4/17/17",
    "numUseful": 6,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 6,
    "reviewScore": 5,
    "reviewText": "in addition to learning cs fundamentals several mvc frameworks functional programming debugging full stack development the list goes on one of the greatest skills we learn is autonomy the ability to be given a task or come up with one that requires using technologies weve never seen before and build it to break down understand research learn plan build and optimize our way to a solution it is a profound skill that allows us to be given a task in any language or framework and confidently say great ill spin it up"
  },
  {
    "id": 28,
    "photoID": "F42",
    "gender": "F",
    "username": "Caroline N.",
    "cityState": "Boise, ID",
    "numFriends": 13,
    "numReviews": 3,
    "numPhotos": 0,
    "date": "9/4/17",
    "numUseful": 4,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 4,
    "reviewScore": 5,
    "reviewText": "hack reactor isnt perfect and doesnt try to be perfect this desire to constantly improve by what they call rapid iteration education is one of their greatest strengths the staff is completely ready to uproot something theyve been doing at hack reactor since it was founded and replace it with something that will improve the quality of our education i saw this happen multiple times during my cohort and it was always in our best interest"
  },
  {
    "id": 20,
    "photoID": "F43",
    "gender": "F",
    "username": "Mallory O.",
    "cityState": "Santa Ana, CA",
    "numFriends": 92,
    "numReviews": 7,
    "numPhotos": 8,
    "date": "9/21/17",
    "numUseful": 9,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 11,
    "reviewScore": 5,
    "reviewText": "empower yourself to solve problems\nhack reactors philosophy is to turn students into autonomous learners and they do a great job facilitating this mindset i realized that i am capable of learning anything and that by taking personal responsibility for my learning i could accelerate my growth and overcome technical challenges"
  },
  {
    "id": 64,
    "photoID": "F44",
    "gender": "F",
    "username": "Paulina P.",
    "cityState": "Rochester, NY",
    "numFriends": 8,
    "numReviews": 8,
    "numPhotos": 0,
    "date": "10/16/17",
    "numUseful": 4,
    "numFunny": 0,
    "numCool": 0,
    "numVotes": 4,
    "reviewScore": 5,
    "reviewText": "surround yourself with brilliant and motivated people\nhack reactors admissions process is rigorous and the end result is that all of my cohort mates were brilliant motivated great people to be around"
  },
  {
    "id": 70,
    "photoID": "F45",
    "gender": "F",
    "username": "Ashlynn Q.",
    "cityState": "Houston, TX",
    "numFriends": 57,
    "numReviews": 3,
    "numPhotos": 87,
    "date": "11/21/17",
    "numUseful": 3,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 4,
    "reviewScore": 5,
    "reviewText": "best decision of my life all the hype is true i believe hack reactor is the pioneer for what will soon become the norm in education it was an entire college experience and then some crushed into 6 months including precourse work it was miles above anything i experienced while getting my undergraduate degree and after leaving i feel more confident in my abilities than i thought i could what makes hack reactor so great are the hearts they have the best minds on changing the education industry but more importantly they have the best hearts on it hack reactor is not for you if you feel like you just want to get in and get out the best way to be successful is coming in with an open mind and love for being part of a team just amazing"
  },
  {
    "id": 54,
    "photoID": "F46",
    "gender": "F",
    "username": "Amy R.",
    "cityState": "Detroit, MI",
    "numFriends": 74,
    "numReviews": 8,
    "numPhotos": 28,
    "date": "11/22/17",
    "numUseful": 6,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 9,
    "reviewScore": 5,
    "reviewText": "after hack reactor i am even more inspired to learn\ni am doing a deeper dive into more complex data structures algorithm analysis and fullstack development i am also planning to python when i have extra time"
  },
  {
    "id": 91,
    "photoID": "F47",
    "gender": "F",
    "username": "Heaven S.",
    "cityState": "Laredo, TX",
    "numFriends": 21,
    "numReviews": 9,
    "numPhotos": 1,
    "date": "6/13/18",
    "numUseful": 7,
    "numFunny": 2,
    "numCool": 1,
    "numVotes": 10,
    "reviewScore": 5,
    "reviewText": "the curriculum was amazing i felt like i was in a situation where i was constantly uncomfortable with the pace of the class but never uncomfortable enough to want to call it quits as you start getting comfortable with the unknown hack reactor will throw you into the project period where you really start getting uncomfortable and learn how to become an autonomous software engineer for me personally i thought that the project period was an invaluable part of hack reactors curriculum"
  },
  {
    "id": 36,
    "photoID": "F48",
    "gender": "F",
    "username": "Lesly T.",
    "cityState": "Lincoln, NE",
    "numFriends": 81,
    "numReviews": 8,
    "numPhotos": 26,
    "date": "9/7/18",
    "numUseful": 6,
    "numFunny": 0,
    "numCool": 1,
    "numVotes": 7,
    "reviewScore": 5,
    "reviewText": "Man, if I had known about this, I would've dropped out of college. I feel like I've wasted so much time and money. Definitely recommend doing this rather than a university program. "
  },
  {
    "id": 52,
    "photoID": "F49",
    "gender": "F",
    "username": "Rachael U.",
    "cityState": "Phoenix, AZ",
    "numFriends": 2,
    "numReviews": 3,
    "numPhotos": 23,
    "date": "11/8/18",
    "numUseful": 0,
    "numFunny": 1,
    "numCool": 1,
    "numVotes": 2,
    "reviewScore": 5,
    "reviewText": "If there is one thing people should know about Hack Reactor, it's that HR prioritizes the success of its students over their comfort. It is inevitable that you will be consistently pushed beyond your limits, and if you are not prepared, you'll have a difficult time here, emotionally or otherwise. To that end, I would caution for only people who are willing to improve themselves (on a technical and social level) to apply to Hack Reactor. "
  },
  {
    "id": 58,
    "photoID": "F50",
    "gender": "F",
    "username": "Brynlee V.",
    "cityState": "San Bernardino, CA",
    "numFriends": 38,
    "numReviews": 5,
    "numPhotos": 6,
    "date": "3/3/19",
    "numUseful": 5,
    "numFunny": 1,
    "numCool": 0,
    "numVotes": 6,
    "reviewScore": 5,
    "reviewText": "Fast forward to now. I graduated about 3 weeks ago. I was ready for a 3 month long process until I received an offer. First 2 weeks, I was applying through the front door. 0 replies. But, you see, Hack Reactor does this awesome thing called Hiring Day, basically the career fair at the end. It's like a speedway into a company. I seriously lucked out and a few of them were interested in me. I managed to do well enough in the interviews such that I received offers. And that statistic you probably read about $$$, lets just say there is a ridiculous amount of money in tech. So the pull that Hack Reactor (or rather anyone who can get you in the front door) has is incredible. "
  }
 ];

 module.exports = sampleReviews;